version: '3.8'

services:
  photobio-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Add your environment variables here or use env_file
    env_file:
      - .env
    restart: unless-stopped
